language: node_js
node_js:
  - "10"
install:
  - npm install now
  - ./node_modules/.bin/now --prod -C -t $NOW_TOKEN --env API_BASE_URL=$API_BASE_URL --env API_TOKEN=$API_TOKEN --env API_FEED_ID=$API_FEED_ID --env API_CLIENT_ID=$API_CLIENT_ID --env API_CLIENT_SECRET=$API_CLIENT_SECRET --env DB_CONNECTION_STRING=$DB_CONNECTION_STRING
